version: '2.0'
services:
  redis:
    container_name: ipp_redis
    image: redis
    ports:
    - "6379:6379"
    networks:
    - ipp_network
  server:
    container_name: ipp_server
    build:
      context: .
      dockerfile: server.Dockerfile
    image: edgejay/ipp-server
    environment:
    - DOCKER_ENV=true
    - REDIS_HOST=ipp_redis
    ports:
    - "4000:4000"
    networks:
    - ipp_network
  nginx:
    container_name: ipp_nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: edgejay/ipp-nginx
    environment:
    - REACT_APP_DOCKER_ENV=true
    ports:
    - "8080:80"
    networks:
    - ipp_network
networks:
  ipp_network:
    driver: bridge