version: '2.0'
services:
  redis:
    container_name: ipp_redis
    image: redis
    ports:
    - "6379:6379"
    networks:
    - ipp_network
  server:
    container_name: ipp_server
    build: ./packages/server
    image: edgejay/ipp-server
    ports:
    - "4000:4000"
    networks:
    - ipp_network
  nginx:
    container_name: ipp_nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: edgejay/ipp-nginx
    ports:
    - "8080:80"
    networks:
    - ipp_network
networks:
  ipp_network:
    driver: bridge